FROM store/oracle/serverjre:8

RUN yum -y install git
WORKDIR /home
RUN git --version
RUN git clone https://github.com/coreyjjames/minecraft-network.git

WORKDIR /home/minecraft-network/Lobby-Instance

RUN yum -y install screen