apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-bungeecord
  namespace: default
  labels:
    app: minecraft-bungeecord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-bungeecord
  template:
    metadata:
      labels:
        app: minecraft-bungeecord
    spec:
      containers:
        - name: minecraft-bungeecord
          image: registry.digitalocean.com/coreyjjames-ocean/minecraft-bungeecord:latest
          command: ["java"]
          args: ["-Xms1G", "-Xmx1G", "-jar" , "BungeeCord.jar"]
      tolerations:
        - key: "server"
          operation: "Equal"
          value: "bungeecord"
          effect: "NoSchedule"


              