apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-lobby
  namespace: default
  labels:
    app: minecraft-lobby
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-lobby
  template:
    metadata:
      labels:
        app: minecraft-lobby
    spec:
      containers:
        - name: minecraft-lobby
          image: coreyjjames/minecraft-lobby:latest