apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-uhc
  namespace: default
  labels:
    app: minecraft-uhc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-uhc
  template:
    metadata:
      labels:
        app: minecraft-uhc
    spec:
      containers:
        - name: minecraft-uhc
          image: coreyjjames/minecraft-uhc:latest